### ISSUE TITLE
Miss spelling in web page

### ISSUE THREAD

**Issue by Megastrik3** [thebigpotatoe/Super-Simple-RGB-WiFi-Lamp#42]
While exploring the web site I found that there was a miss spelling of the word "the" in the clock mode.  It was accidentally spelled "teh". This error can be found on line 1002 of the Web_Page.ino file. If you would like I can attach the fixed version of the file.

**Comment by thebigpotatoe** [comment]
Awesome thanks for the heads up. If you would like to learn about contributing to code, you can [create a pull request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) on this which I can merge into the code and it shows you as a contributor.

Otherwise I'll go ahead and just fix it.
