### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by StefaanVanDooren** [thebigpotatoe/Super-Simple-RGB-WiFi-Lamp#8]
This site has some nice effects : https://www.tweaking4all.com/hardware/arduino/adruino-led-strip-effects/#RequiredLibraryNeoPixelorFastLED

Can you add some? I'm looking at adding it myself, but it isn't yet working as expected.

**Comment by thebigpotatoe** [comment]
Hmm. I like some of these. But I think half are useful for applications using a straight line of leds rather that the square back light that i use. 

I do like the idea of the snow fall one, I have build that before for another project and may do it again for this one. Was there one that interested you?

And I know that implementing your own modes is no small feat. whilst I tried to make the code easy to just install, I made a smaller effort on allowing people to easily create modes of their own. This I suppose is due to the implementation of the data storage, messaging and the website focusing on a working and efficient model rather than a customisable one.

Having said this, if you have a crack at implementing your own mode, send a pull request and we can see if we can work through the bugs to get it working.

**Comment by StefaanVanDooren** [comment]
I do like the fadein-fadeout (but not to fast), the running lights, color wipe (circle, so first fill it up, then clear), and perhaps the theatherchase...
I tried a few, but they do work nicely on there own, but not with your website and switching from one to another, because they block the program....still working that out....

**Comment by thebigpotatoe** [comment]
Oh awesome. If you managed to get the LED's to light up the way you want the hard part is already done.

Maybe i can write up a small section, or post here how to modify the website and the arduino code to add any mode you want completely.

**Comment by StefaanVanDooren** [comment]
I managed to add one  mode replacing the visualiser (don't have a good input signal), but I don't quiet understand the webserver coding. so a little tutorial would be nice.
Also, I would like to be the brightness a global setting like the fadetime. I changed the code for colour and belt curve to use the brightness from the rainbow, but here again, I can't figure out the webserver coding....

**Comment by StefaanVanDooren** [comment]
Managed to get the brightness as a global setting for all modes.
Looking at how to add a mode now.

What is the best way to give you my changes? I started with a copy I downloaded, so not yet using github....

**Comment by thebigpotatoe** [comment]
Best way, and frankly only way, i will accept changes will be via github pull requests. This will make it easy to merge and track changes to the project. 

Its not to hard to start now. What u need is github desktop, use it to clone this repository, paste in the code differences, then push back to github using github desktop.

You can then on the website send a pull request to me. This will allow me to see changes side by side and automate merging.

**Comment by thebigpotatoe** [comment]
I'm going to close this issue as we are a few commits ahead now. Have a look at #25 where we added an easier way to add modes. Hopefully soon I can also add an easy method for updating the website too
